title: Abhishek Jha
url: "https://abskjha.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/abskjha"
footer_text: "Abhishek Jha (c) 2018"

profile_details: "Abhishek Jha  <br/>
MS (by research), Computer Science  <br/>
<a href="http://cvit.iiit.ac.in">Centre for Visual Information Technology (CVIT)</a>  <br/>
<a href="http://iiit.ac.in">IIIT Hyderabad</a>  <br/>

profile_picture_path: "sherlock.jpg"

sass:
    style: compressed
    sass_dir: _sass

include: ["_includes"]