title: Abhishek Jha
url: "https://abskjha.github.io"
baseurl: "/researcher"

markdown: kramdown

tracking_id: #

footer: No
footer_url: "https://github.com/abskjha"
footer_text: "Page adapted by Abhishek Jha"

sass:
    style: compressed
    sass_dir: _sass
