title: Researcher
url: "https://abskjha.github.io"
baseurl: "/index.html"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/abskjha"
footer_text: "Page adapted by Abhishek Jha"

sass:
    style: compressed
    sass_dir: _sass
