title: Abhishek Jha
url: "https://abskjha.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/abskjha"
footer_text: "Abhishek Jha (c) 2018"

profile_details: Abhishek Jha  
MS (by research), Computer Science  
[Centre for Visual Information Technology (CVIT)](http://cvit.iiit.ac.in)  
[IIIT Hyderabad](http://iiit.ac.in)

profile_picture_path: "sherlock.jpg"

sass:
    style: compressed
    sass_dir: _sass

include: ["_includes"]